manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson/
    - name: nmunnich
      url-base: https://github.com/nmunnich/zmk-component-rp2040-zero
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-component-rp2040-zero 
      remote: nmunnich
      revision: main
  self:
    path: config
